"use client";
import "bootstrap/dist/css/bootstrap.min.css";

import React, { useState, useEffect } from "react";
import axios from "axios";
import Link from "next/link";
  
export default function Home(data) {
  const [users, setUsers] = useState([]);
  const [datas, setDatas] = useState([])
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
  const url = 'https://api.jsonsilo.com/public/d1166487-7a88-4c53-9be7-94d20dbd04d4';
    const headers = {
        'Content-Type': 'application/json'
    };

    axios.get(url, { headers: headers })
    .then(response => {
        console.log(response.data);
    })
    .catch(error => {
        console.error('There was an error with the request:', error);
    });
  }, []);





  const deleteUser = (id) => {
    axios.delete(`http://localhost:5000/users/${id}`)
      .then(() => {
        const updatedUsers = users.filter(user => user.id !== id);
        setUsers(updatedUsers);
      })
      .catch(error => {
        console.error('Error deleting user:', error);
      });
  };

  return (
     <>
      <Head>
        <title>JSON SILO [Sample]</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      {data && data.map((v, k)=> (
        <div key={k}>
          <p>{v.name}</p>
          <p>{v.email}</p>
        </div>
        
      ))}
    </>
  )
}
